version: '3'

services:
    web:
      build: .
      ports: 
          - 8000:8000
      volumes:
          - .:/comments_service
      command: python manage.py runserver 0.0.0.0:8000
      env_file:
          - .env